[project]
name = "flight-prices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yauckbur", email = "59585428+yauckbur@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
flight-prices = "flight_prices:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
